
osx_image: xcode9.2
language: swift
sudo: required

script:
  - xcodebuild clean build test
    -project "LeptirFrame.xcodeproj"
    -scheme "LeptirFrame"
    -sdk "iphonesimulator11.3"
    -destination "platform=iOS Simulator,name=iPhone 8,OS=11.2.6"
    -configuration Release
    -enableCodeCoverage YES
    CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
